# Generated by Django 4.1.5 on 2023-01-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0012_metal_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_cart',
            name='diamond_size',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user_cart',
            name='weight',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user_cart',
            name='quantity',
            field=models.TextField(blank=True),
        ),
    ]
