# Generated by Django 4.1.5 on 2023-01-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0013_user_cart_diamond_size_user_cart_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('amount', models.TextField()),
                ('provider_order_id', models.TextField()),
            ],
        ),
    ]
