# Generated by Django 4.1.5 on 2023-01-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0014_payment_status_payments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Razorpayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.TextField(blank=True)),
                ('razorpay_payment_id', models.TextField()),
                ('razorpay_signature', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='payments',
            name='transaction_id',
            field=models.TextField(blank=True),
        ),
    ]
