# Generated by Django 4.1.5 on 2023-01-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0016_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(blank=True)),
                ('date', models.TextField(blank=True)),
                ('product_img', models.TextField(blank=True)),
                ('product_name', models.TextField(blank=True)),
                ('product_code', models.TextField(blank=True)),
                ('product_price', models.TextField(blank=True)),
                ('rating', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Payment_status',
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
        migrations.DeleteModel(
            name='Razorpayment',
        ),
    ]
