# Generated by Django 4.1.5 on 2023-01-18 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0017_order_status_delete_payment_status_delete_payments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_status',
            name='rating',
        ),
    ]
