# Generated by Django 4.1.5 on 2023-01-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0018_remove_order_status_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order_status',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order_status',
            name='user_id',
            field=models.TextField(blank=True),
        ),
    ]
